.PHONY: clean All

All:
	@echo "----------Building project:[ SortingAlgos - Debug ]----------"
	@cd "Sorting_algos" && "$(MAKE)" -f  "SortingAlgos.mk"
clean:
	@echo "----------Cleaning project:[ SortingAlgos - Debug ]----------"
	@cd "Sorting_algos" && "$(MAKE)" -f  "SortingAlgos.mk" clean
